### PR TITLE
Changed google urls used for health check test to work on CA and US m…

### PR DESCRIPTION
**Pull request by girwin**
…achines

### CODE REVIEW

**Comment by ChaseFlorell** [comment]
were the tests failing on the build server? Those tests were added to ensure the Examples matched the expected behavior.  
https://futurestatemobile.github.io/poshBAR/#Invoke-WebHealthCheck

**Comment by girwin** [comment]
Yes, the tests fail on a server hosted in the US because requesting google.com on http results in a 301, not a 302. I guess I should have updated the docs. Not sure what's best here, could perhaps test on a host that doesn't flip to .ca

**Comment by ChaseFlorell** [comment]
What about testing against a KNOWN response url?  
http://httpstat.us/200 

It would require updating the docs to match, since the test is asserting the example.

**Comment by girwin** [comment]
Ok, no need to yell, I closed it... :-)

**Pull request closed without merging**
