### PR TITLE
MSBuild.ps1: handle spaces in paths.

### PR DESCRIPTION
**Pull request by alexandertsang**
Modify msbuild command-lines to handle spaces in paths.

### CODE REVIEW

**Comment by ChaseFlorell** [comment]
Hey, thanks for the PR... I see what you're doing in there, but might you explain the benefit? I'm genuinely curious.

**Comment by alexandertsang** [comment]
When I try to run the build inside a path that has spaces, the current command breaks. I.e. if my project is at _C:\Work\Company Name\Project\src\myapp.csproj_, the space between _Company Name_ causes the msbuild command in MSBuild.ps1 to think there are two separate arguments: _C:\Work\Company_ and _Name\Project\src\myapp.csproj_.

I could rename my folder hierarchy to work around it, but it would be great if the scripts handled this case automatically. I haven't looked to see if any of the other scripts would need a similar change, but this was the one that I happened to run up against. I hope that answers your question, and thanks for looking!

**Comment by ChaseFlorell** [comment]
Ah, good point, and one that I never thought of. Yes, there are other places that would do the same. Have you tested that this works? If so, I'll merge without further test.

**Comment by alexandertsang** [comment]
Yes I've tested this in one of my projects.

**Pull request merged**
